### ISSUE TITLE
Make logos bigger

### ISSUE THREAD

**Issue by interactivellama** [salesforce/salesforce.github.io#13]
Make the logo as big as you can! https://youtu.be/5AxwaszFbDw?t=17s

Also adds link to Design System React:
<img width="761" alt="screen shot 2018-03-20 at 1 16 02 am" src="https://user-images.githubusercontent.com/1290832/37640892-26847236-2bdd-11e8-8eb3-f876d2004720.png">

I'll try to PR this tomorrow.

**Comment by daminisatya** [comment]
I think this is fixed as part of #14 ?
